/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/



#include <iostream>
#include <vector>
using namespace std;

int main()


{
   int index=2;

   int   current=2;
   int  one_back=1;
   int two_back=0;

   int total=0;

       vector<int> Fibonacci (3,1);
      while (Fibonacci[current]<4000000) {

        current=(index%3);
        one_back=((index-1)%3);
        two_back=((index-2)%3);
        Fibonacci[current]=Fibonacci[one_back]+Fibonacci[two_back];

        if (Fibonacci[current]%2==0){
            total+=Fibonacci[current];
        }
        index+=1;
      }

 cout<<"The answer is "<<total<<endl;

    return 0;
}
