"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:
4613732
Completed on Mon, 21 Jan 2013, 22:23

"""
import time
ras=time.time()
current=2
one_back=1
two_back=0
index=2
total=0
Fibonacci = [1]*3

while (Fibonacci[current]<4000000):

    current=(index%3)
    one_back=((index-1)%3)
    two_back=((index-2)%3)
    nextSum=Fibonacci[one_back]+Fibonacci[two_back]
    Fibonacci[current]=nextSum
    if nextSum%2==0:
        total+=nextSum
    index+=1

print "The answer is ",total

print "The time took ",time.time()-ras
