"""Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?


Answer:
76576500
Completed on Wed, 23 Jan 2013, 03:16
Go to the thread for problem 12 in the forum.
"""


import time
import sys
r=time.time()


 
 
 
  
def divisors(n):
    end=int(n**.5)+1
    facts=2
    
    for i in range(2,end):
          
            if n%i==0:
                facts+=2
               
          
    if facts>500:
        print "done"
        print "the answer is TriangleNumber ",n, " With : ",facts
         
        print time.time()-r
        sys.exit()
   
     
       
 
 
 
for q in range(1,2200000):
    h = (q*(q+1.0))/2.0
   
    divisors(h)
      
    
 
 
    
 
